name: "Terraform Infra Provision"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      confirm:
        description: 'Should TF script be applied? (yes or no)'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-3
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform plan -out=tfplan
          else
            # Comment out EKS and VPC files for plan
            sed -i 's/^/# /' vpc.tf
            sed -i 's/^/# /' eks.tf
          
            # Modify outputs.tf
            sed -i '/^output "cluster_name" {/,/^}/ s/^/# /' outputs.tf
            sed -i '/^output "cluster_endpoint" {/,/^}/ s/^/# /' outputs.tf
          
            # Modify providers.tf
            sed -i '/^provider "kubernetes" {/,/^}/ s/^/# /' providers.tf
            sed -i '/^provider "helm" {/,/^}/ s/^/# /' providers.tf
          
            terraform plan -out=tfplan
          fi

      - name: Apply or Destroy Terraform Configuration
        if: ${{ github.event.inputs.confirm == 'yes' }}
        run: |
          terraform apply --auto-approve tfplan
#          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
#            terraform apply --auto-approve tfplan
#          else
#            terraform apply --auto-approve
