name: "Terraform Infra Provision"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      confirm:
        description: 'Should TF script be applied? (yes or no)'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-3
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
#          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Debug - List Files
        run: ls -al

      - name: Terraform Plan
        id: plan
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform plan -no-color -out=plan.out -detailed-exitcode 
          else
            echo "Commenting out resources for destroy plan"
            # Comment out EKS and VPC files for plan
            sed -i 's/^/# /' vpc.tf
            sed -i 's/^/# /' eks.tf
          
            echo "Modified vpc.tf and eks.tf"
            cat vpc.tf
            cat eks.tf

            # Modify outputs.tf
            sed -i '/^output "cluster_name" {/,/^}/ s/^/# /' outputs.tf
            sed -i '/^output "cluster_endpoint" {/,/^}/ s/^/# /' outputs.tf
          
            echo "Modified outputs.tf"
            cat outputs.tf

            # Modify providers.tf
            sed -i '/^provider "kubernetes" {/,/^}/ s/^/# /' providers.tf
            sed -i '/^provider "helm" {/,/^}/ s/^/# /' providers.tf
          
            echo "Modified providers.tf"
            cat providers.tf
          
            terraform plan -no-color -out=plan.out
          fi

      - name: Apply Terraform Configuration
        if: ${{ github.event.inputs.confirm == 'yes' }}
        run: terraform apply --auto-approve tfplan
